### ISSUE TITLE
Do you have any QXDM4 interface document?

### ISSUE THREAD

**Issue by jufei** [sumitrastogi76/QXDM4_script_for_log_collection#1]
Hi:
   I am useing the QXDM to control the UE. And same as you, I wish to use the Automation Interface. But I do not have the interface document, so I don't know the function list of the interface.

  Would you please tell me if you have such kind of document?

Thanks in advance.

**Comment by sumitrastogi76** [comment]
Sorry jufei, I don't have any such document.

**Comment by jufei** [comment]
ok and thanks

发自我的 iPhone

在 2018年12月18日，下午7:26，SUMIT RASTOGI <notifications@github.com<mailto:notifications@github.com>> 写道：


Sorry jufei, I don't have any such document.

**Comment by sumitrastogi76** [comment]
as per above discussion, I am closing issue.
